import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Detailed descriptions based on Wikipedia
const descriptions = {
  "Tirupati Balaji Temple": "One of the most visited and sacred temples in India, dedicated to Lord Venkateswara. Located on the Tirumala hills, it receives millions of pilgrims annually. The temple is famous for its ornate architecture and the tradition of head-shaving and offerings.",
  "Visakhapatnam Beach": "A beautiful coastal city in Andhra Pradesh known for its scenic beaches and maritime heritage. The city is home to the Naval Museum and offers water sports, dolphin spotting, and various beach activities.",
  "Araku Valley": "A picturesque hill station known for its coffee plantations, scenic tea gardens, and stunning waterfalls. The valley is home to the Arakku tribe and offers beautiful monsoon views, scenic train rides through tribal villages.",
  "Lepakshi Temple": "A historic 16th-century temple famous for its unique hanging pillar architecture and intricate stone carvings. The temple is known for murals depicting various Hindu deities and the architecture blend of Vijayanagara and Dravidian styles.",
  "Tawang Monastery": "The largest and most significant Tibetan Buddhist monastery in India, founded in 1680. It houses over 300 monks and features stunning architecture with gilded roofs, intricate murals, and a 27-foot gold statue of Buddha.",
  "Ziro Valley": "Famous for its scenic rice fields and the unique culture of the Apatani tribe who practice sustainable agriculture. The valley is a biodiversity hotspot with traditional village life and the annual Ziro Festival of Music.",
  "Sela Pass": "A high-altitude mountain pass at 13,700 feet connecting Tawang with lower Arunachal Pradesh. It's known for the scenic Sela Lake and breathtaking views of the Eastern Himalayas, often snow-covered.",
  "Namdapha National Park": "Rich in biodiversity with endangered species like the clouded leopard and red panda. The park offers trekking trails, wildlife spotting, and pristine forest landscapes alongside the Noa-Dihing river.",
  "Kaziranga National Park": "Famous as the home to the Indian one-horned rhinoceros with the world's largest population. It's a UNESCO World Heritage Site offering jeep safaris, wildlife photography, and bird watching with over 450 bird species.",
  "Majuli Island": "The world's largest river island on the Brahmaputra, famous for its unique Satras (monasteries) and artistic traditions. The island is home to Mishing tribe community and offers cultural tourism and riverine experiences.",
  "Kamakhya Temple": "A sacred Hindu temple dedicated to the goddess Kamakhya, one of the oldest pilgrimage sites in Assam. Known for its unique architecture and the Ambubachi festival attracting thousands of devotees.",
  "Chitrakote Falls": "India's widest waterfall spanning 980 meters, often called the 'Indian Niagara Falls'. The waterfall is spectacular during monsoon season and offers natural pools for bathing.",
  "Kanger Valley National Park": "Famous for its network of limestone caves including Kutumsar and Kailash caves. The park offers trekking, cave exploration, and wildlife viewing with rich tribal culture.",
  "Bodh Gaya": "The most sacred Buddhist pilgrimage site where Buddha attained enlightenment under the Bodhi tree. Features the magnificent Mahabodhi Temple, a UNESCO World Heritage Site built in the 5th-6th century.",
  "Nalanda University": "An ancient center of learning established in the 5th century, one of the world's first universities. The ruins showcase the educational heritage with remains of hostels, temples, and libraries.",
  "Baga Beach": "A popular beach known for its vibrant nightlife, water sports, and beachside shacks. The beach offers parasailing, windsurfing, and a lively atmosphere with many cafes and restaurants.",
  "Dudhsagar Falls": "A spectacular four-tiered waterfall with a height of 310 meters cascading through the Western Ghats. Best viewed during monsoon season, it offers trekking opportunities and natural pools.",
  "Basilica of Bom Jesus": "A UNESCO World Heritage church in Old Goa, famous for housing the relics of St. Francis Xavier. The church showcases baroque architecture and remains one of Asia's oldest churches built in 1605.",
  "Anjuna Flea Market": "A famous market held every Wednesday featuring unique local handicrafts, antiques, and souvenirs. The market represents Goa's cultural diversity and attracts tourists and locals alike.",
  "Rann of Kutch": "A vast white salt desert famous for the annual Rann Utsav festival during winter. The stark white landscape creates a unique ecosystem and offers camping and cultural experiences.",
  "Gir National Park": "The last refuge of the Asiatic lion with a population of around 600 lions. The park offers jeep safaris, nature trails, and wildlife photography opportunities.",
  "Somnath Temple": "One of the twelve Jyotirlingas and one of the most significant Hindu shrines. The temple has been rebuilt multiple times and showcases stunning architecture overlooking the Arabian Sea.",
  "Kurukshetra": "The ancient battlefield where the Mahabharata war was fought, mentioned in Hindu scriptures. The region has numerous temples and historical sites connected to the epic.",
  "Sultanpur National Park": "A bird sanctuary near Gurgaon hosting migratory birds from Central Asia during winter. The park is ideal for bird watching with over 250 bird species recorded.",
  "Manali": "A popular hill station known for adventure sports like paragliding and skiing during winters. The town offers scenic trekking trails, the beautiful Solang Valley, and access to Rohtang Pass.",
  "Shimla": "A colonial hill station famous as the summer capital during British rule. Known for its pleasant climate, Mall Road shopping, and the Ridge offering panoramic Himalayan views.",
  "Spiti Valley": "A cold desert mountain valley with zero vegetation, often called the 'Land of Gods'. The valley offers adventure tourism with trekking, monasteries, and pristine mountain landscapes.",
  "Hundru Falls": "One of the highest waterfalls in India with a height of 98 meters, located on the Subarnarekha river. The scenic waterfall offers natural pools and beautiful surroundings.",
  "Betla National Park": "A wildlife sanctuary with forests, grasslands, and the historic Palamu Fort. The park is habitat to tigers, elephants, and over 250 bird species.",
  "Hampi": "UNESCO World Heritage Site featuring ancient ruins of the Vijayanagara Empire capital. The town showcases remarkable stone architecture with temples, bazaars, and royal structures.",
  "Mysore Palace": "A grand royal palace showcasing Indo-Saracenic architecture with intricate carvings and decorations. The palace illumination during Dasara festival attracts thousands of visitors.",
  "Coorg": "A picturesque hill station famous for coffee plantations, lush greenery, and cascading waterfalls. The region offers plantation visits, trekking, and adventure sports.",
  "Gokarna Beach": "A peaceful beach alternative to Goa, known for its laid-back atmosphere and scenic beauty. Popular for backpackers with various beach options like Om Beach and Half Moon Beach.",
  "Bandipur National Park": "A tiger reserve known for wildlife viewing and trekking through pristine forests. The park has excellent infrastructure for safari and camping experiences.",
  "Jog Falls": "One of India's highest waterfalls divided into four cascades during monsoon season. The waterfall creates a misty landscape and offers scenic viewpoints.",
  "Alleppey Backwaters": "A scenic network of canals, lagoons, and lakes offering houseboat cruises. The backwaters are famous for the peaceful green landscape and authentic village life.",
  "Munnar": "A scenic hill station with tea plantations, rolling hills, and cool climate. Known for the Eravikulam National Park home to endangered Nilgiri tahr.",
  "Wayanad": "A hill station with lush forests, waterfalls, and wildlife sanctuaries. Famous for adventure activities, spice plantations, and the unique Edakkal Caves.",
  "Kovalam Beach": "A crescent-shaped beach with coconut palms and scenic lighthouse offering panoramic views. Popular for swimming, water sports, and sunbathing.",
  "Thekkady": "Home to the Periyar Wildlife Sanctuary, famous for tiger and elephant sightings. The sanctuary offers boat rides through the scenic lake with rich biodiversity.",
  "Fort Kochi": "A historic port city with colonial architecture showcasing Chinese fishing nets and historic buildings. The town is known as the 'Queen of the Arabian Sea' with spice markets.",
  "Khajuraho Temples": "UNESCO World Heritage Site famous for intricate erotic sculptures and architectural excellence. The temples showcase the artistic and architectural brilliance of the Chandela dynasty.",
  "Bandhavgarh National Park": "A premier tiger reserve with highest tiger density and excellent safari infrastructure. Known for the historic Bandhavgarh Fort within the park boundaries.",
  "Sanchi Stupa": "A UNESCO World Heritage Site housing one of the oldest Buddhist monuments with intricate stone gateways. Built during Ashoka's reign, it's a masterpiece of ancient Indian art.",
  "Pachmarhi": "A scenic hill station with deep valleys, waterfalls, and natural caves. Known for trekking trails and the spectacular Bee Falls and Dhoopgarh viewpoint.",
  "Bhimbetka Caves": "UNESCO World Heritage Site featuring prehistoric rock shelters with ancient paintings. The caves showcase the evolution of human artistic expressions over 30,000 years.",
  "Kanha National Park": "Inspired the Jungle Book, the park is known for tiger sightings and pristine forests. Offers excellent jeep safaris and trekking opportunities.",
  "Mumbai": "The financial capital of India, known for its iconic landmarks including Gateway of India and Marine Drive. The city offers diverse culture, Bollywood industry, and vibrant nightlife.",
  "Ajanta Caves": "UNESCO World Heritage Site featuring ancient Buddhist caves with wall paintings and sculptures. Carved into a horseshoe-shaped cliff, the caves showcase Buddhist art over centuries.",
  "Ellora Caves": "Rock-cut architecture marvel with Hindu, Buddhist, and Jain temples in one complex. The Kailashanatha Temple is the largest single rock excavation in the world.",
  "Lonavala": "A hill station known for scenic valleys, caves, and adventure sports like paragliding. Popular for weekend getaway with trekking, rock climbing, and historical sites.",
  "Mahabaleshwar": "A scenic hill station famous for strawberry plantations and panoramic viewpoints. Known for the cool climate, Arthur's Seat, and adventure activities.",
  "Alibaug Beach": "A coastal getaway near Mumbai with golden sand beaches and water sports. Known for Kolaba Fort and peaceful atmosphere.",
  "Loktak Lake": "Unique floating lake with phumdis (islands) and rich biodiversity. Home to the endangered Sangai deer and offers boat rides through scenic landscape.",
  "Keibul Lamjao National Park": "The world's only floating national park on Loktak Lake, sanctuary to endangered species. Offers unique wildlife viewing and nature photography opportunities.",
  "Imphal": "The capital of Manipur known for its strategic location and cultural heritage. Features ancient temples, historical sites, and colorful markets.",
  "Kangla Fort": "Historic fortress with ancient gates and spiritual significance in Manipur. Located strategically overlooking the city with beautiful gardens.",
  "Ukhrul": "A scenic hill station with verdant forests and breathtaking views. Popular for trekking and experiencing tribal Naga culture.",
  "Shirui Hills": "Famous for the endemic Shirui Lily blooming only in May-June. The hills offer spectacular scenic beauty and trekking opportunities.",
  "Cherrapunji": "One of the wettest places on Earth with heavy monsoon rainfall creating lush green landscape. Famous for living root bridges and Nohkalikai Falls.",
  "Shillong": "The capital of Meghalaya known as the 'Scotland of India' with pleasant climate. Known for music, waterfalls, and scenic beauty.",
  "Living Root Bridges": "Unique bio-engineered bridges made from living tree roots by local tribes. Ancient engineering marvel and UNESCO cultural heritage.",
  "Dawki River": "A crystal-clear river famous for boating and scenic beauty forming India-Bangladesh border. The river offers unique underwater views during clear water periods.",
  "Mawsmai Caves": "Spectacular limestone caves with underground streams and natural formations. Offers adventure caving experiences with scenic surroundings.",
  "Elephant Falls": "A beautiful multi-tier waterfall near Shillong with scenic trekking trails. Named for a nearby elephant-shaped rock formation.",
  "Aizawl": "The capital of Mizoram known for its scenic hilltop location and tribal culture. Features colorful houses and cultural museums.",
  "Reiek Hills": "Panoramic hilltop offering 360-degree views of surrounding landscape. Popular for trekking and experiencing local Mizo culture.",
  "Phawngpui Peak": "The highest peak in Mizoram offering stunning panoramic vistas. Known for rhododendron forests and adventure trekking.",
  "Vantawng Falls": "The highest waterfall in Mizoram with a height of 750 meters. Creates a spectacular waterfall view during monsoon season.",
  "Tam Dil Lake": "A serene lake surrounded by dense forests offering peaceful atmosphere. Popular for trekking, camping, and nature photography.",
  "Murlen National Park": "Rich in biodiversity with diverse flora and fauna. Offers trekking trails and wildlife viewing opportunities.",
  "Kohima": "The capital of Nagaland known for the Hornbill Festival and war history. Features British-era cemetery and cultural significance.",
  "Dzukou Valley": "A valley of flowers with scenic rhododendron and flowering plants during spring. Popular for trekking and nature photography.",
  "Hornbill Festival": "A major cultural festival celebrating Naga tribal traditions held in December. Features colorful dances, traditional attire, and tribal food.",
  "Japfu Peak": "The second highest peak in Nagaland offering stunning views and adventure hiking. Popular destination for trekking enthusiasts.",
  "Mon District": "Region known for tribal heritage and Naga head-hunting history. Offers cultural tourism and authentic tribal experiences.",
  "Kohima War Cemetery": "WWII memorial housing graves of soldiers from various nations. Maintains records of soldiers killed in Kohima battle.",
  "Konark Sun Temple": "UNESCO World Heritage Site with intricate stone carvings representing the Sun God. A masterpiece of Kalinga architecture built in the 13th century.",
  "Puri Beach": "A popular beach destination famous for Jagannath Temple and Rath Yatra festival. Offers relaxation, water sports, and spiritual significance.",
  "Jagannath Temple": "One of the four most sacred Hindu shrines with the famous Rath Yatra chariot festival. Features 12th-century architecture with 64-meter-high tower.",
  "Chilika Lake": "India's largest coastal lagoon offering boat rides and bird watching. Home to endangered Irrawaddy dolphins and migratory bird species.",
  "Simlipal National Park": "Tiger reserve known for waterfalls and forest trekking trails. Offers jeep safaris and nature experiences.",
  "Dhauli Hills": "Site of Buddhist peace pagoda with historical significance from Ashoka era. Offers panoramic views and peaceful meditation atmosphere.",
  "Golden Temple": "The holiest Sikh shrine with stunning golden architecture reflected in holy pool. Open to all visitors regardless of religion, serves free meals.",
  "Jallianwala Bagh": "Historic garden remembering a tragic massacre during India's independence movement. Now a national memorial maintaining the historical significance.",
  "Wagah Border": "International border between India-Pakistan hosting spectacular change of guard ceremony. Known for patriotic fervor and synchronized border closing.",
  "Amritsar": "A holy city famous for Golden Temple and the Partition Museum. Known for authentic Punjabi cuisine and vibrant markets.",
  "Anandpur Sahib": "A historic religious site associated with Sikh history and the Khalsa formation. Features holy tank and sacred temples.",
  "Patiala": "Royal heritage city known for magnificent palaces and Patiala cuisine. Features Qila Mubarak palace and traditional architecture.",
  "Jaipur": "The 'Pink City' with geometric city planning and stunning pink-colored buildings. Known for Hawa Mahal and royal palaces.",
  "Udaipur": "The 'City of Lakes' featuring stunning lakeside palaces and scenic beauty. Known for Lake Pichola and romantic architectural heritage.",
  "Jaisalmer Fort": "A golden-colored fort in the Thar Desert showcasing Rajasthani architecture. Features narrow lanes, havelis, and panoramic desert views.",
  "Pushkar": "A holy town famous for the annual Pushkar Camel Fair during October-November. Known for Brahma Temple and spiritual atmosphere.",
  "Mount Abu": "The only hill station in Rajasthan offering cool climate and scenic views. Famous for Dilwara Temples and Naked Lake (Nakki Lake).",
  "Thar Desert": "An expansive desert offering safari experiences and desert camps. Known for golden dunes, desert villages, and camel trekking.",
  "Gangtok": "The vibrant capital of Sikkim known for Buddhist monasteries and scenic beauty. Famous for MG Marg shopping street and Rumtek Monastery.",
  "Tsomgo Lake": "A glacial lake offering scenic beauty and reflection of surrounding mountains. Permits required for visiting this pristine high-altitude lake.",
  "Nathula Pass": "A mountain pass at 14,140 feet connecting India with Tibet. Offers stunning Himalayan views and permits-only access.",
  "Yumthang Valley": "A valley of flowers with rhododendron forests and hot springs. One of the most scenic destinations attracting trekkers and nature lovers.",
  "Pelling": "A scenic town in Sikkim offering cultural experiences and mountain views. Known for nearby monasteries and adventure activities.",
  "Rumtek Monastery": "A major Buddhist monastery featuring golden stupas and spiritual ambiance. Important center for Tibetan Buddhism in India.",
  "Meenakshi Temple": "An iconic South Indian temple with 14-tiered gopurams and intricate carvings. One of the oldest functioning temples in India.",
  "Ooty": "The 'Queen of Hill Stations' offering pleasant climate and scenic beauty. Known for botanical gardens and toy train ride.",
  "Kodaikanal": "A popular hill retreat known for coaker's walk and scenic lakes. Famous for pleasant climate and adventure activities.",
  "Mahabalipuram": "UNESCO site featuring ancient rock temples and shore temple. Known for stone sculpture heritage and historical significance.",
  "Rameswaram": "A sacred pilgrimage town famous for Ramanathaswamy Temple and spiritual significance. Known for Dhanushkodi where waters meet.",
  "Marina Beach": "One of the world's longest urban beaches offering relaxation. Known for monuments, lighthouses, and scenic promenades.",
  "Charminar": "An iconic monument and symbol of Hyderabad built in 1591. A four-minaret structure showcasing Indo-Islamic architecture.",
  "Golconda Fort": "A historic fort famous for its architectural brilliance and acoustic engineering. Once the capital of the Qutb Shahi dynasty.",
  "Ramoji Film City": "The world's largest film studio offering studio tours and entertainment experiences. Known as Bollywood's favorite filming location.",
  "Hussain Sagar Lake": "A famous lake with a 32-meter Buddha statue and scenic beauty. Known for boat rides and recreational activities.",
  "Warangal Fort": "Historic fort ruins showcasing medieval Kakatiya architecture. Features the famous Thousand Pillar Temple.",
  "Yadadri Temple": "A famous temple situated atop a hill with panoramic views. Recently renovated with modern amenities.",
  "Ujjayanta Palace": "A royal palace museum showcasing Tripura's royal heritage and artifacts. Features ornamental gardens and historical collections.",
  "Neermahal": "A unique water palace built on an island in Rudrasagar Lake. Showcases Indo-Islamic architecture with beautiful surroundings.",
  "Unakoti": "Rock carvings depicting Hindu deities carved into hillside cliffs. Ancient archaeological site with unique artistic expressions.",
  "Sepahijala Wildlife Sanctuary": "A biodiversity hotspot with diverse flora and fauna including endangered species. Offers nature trails and wildlife viewing.",
  "Jampui Hills": "Scenic hill range known for orange cultivation and panoramic vistas. Popular for trekking during flowering season.",
  "Tripura Sundari Temple": "A famous temple dedicated to the goddess Tripura Sundari. Located in Udaipur (Tripura) with spiritual significance.",
  "Taj Mahal": "The world's most famous monument to love built by Emperor Shah Jahan. UNESCO World Heritage Site showcasing Mughal architecture.",
  "Varanasi": "The holiest Hindu city known for spiritual significance and the Ganges river. Famous for evening Aarti ceremony at ghats.",
  "Ayodhya": "The birthplace of Lord Rama with spiritual and historical significance. Home to the disputed Ram Janmabhoomi temple.",
  "Lucknow": "The 'City of Nawabs' known for Mughal architecture and culinary heritage. Features Bara Imambara and Rumi Darwaza.",
  "Allahabad": "Located at Triveni Sangam where three rivers meet, a major pilgrimage site. Known for Kumbh Mela and spiritual significance.",
  "Mathura": "The birthplace of Lord Krishna with numerous temples and spiritual significance. Known for Holi celebrations and Krishna legends.",
  "Rishikesh": "The yoga capital of India known for yoga ashrams and spiritual retreats. Offers yoga training, adventure sports, and Ganges rafting.",
  "Haridwar": "A holy Hindu city where the Ganges enters the plains. Famous for Har Ki Pauri ghat and spiritual Aarti ceremonies.",
  "Nainital": "A scenic lake town offering boating and scenic mountain views. Known for pleasant climate and adventure activities.",
  "Kedarnath": "A sacred temple located in the Himalayas pilgrimage site of Hindus. Known for the Kedarnath valley trek.",
  "Auli": "India's premiere skiing destination offering winter snow sports. Known for scenic views and adventure activities.",
  "Jim Corbett National Park": "India's first national park famous for tiger conservation. Offers jeep safaris and nature photography opportunities.",
  "Kolkata": "The cultural capital of India known for literature, arts, and architecture. Features Victoria Memorial and cultural heritage.",
  "Darjeeling": "The queen of hill stations famous for tea gardens and scenic beauty. Known for toy train ride and panoramic mountain views.",
  "Sundarbans": "The world's largest mangrove forest and tiger reserve. UNESCO World Heritage Site offering unique ecosystem experiences.",
  "Howrah Bridge": "An iconic bridge spanning the Hooghly River in Kolkata. One of India's busiest bridges with unique steel architecture.",
  "Kalimpong": "A charming hill town known for religious diversity and scenic beauty. Popular for adventure tourism and flower cultivation.",
  "Digha Beach": "A popular beach destination near Kolkata offering relaxation. Known for fresh seafood and beach walks.",
  "Radhanagar Beach": "One of Asia's best beaches known for pristine white sand. Popular for water sports, diving, and snorkeling.",
  "Cellular Jail": "A historic colonial prison museum in Port Blair. Important heritage site recording India's freedom struggle.",
  "Havelock Island": "A picturesque island famous for water sports and diving. Known for Radhanagar Beach and crystal-clear waters.",
  "Neil Island": "A peaceful island escape with beautiful beaches and limited tourists. Known for natural bridge and scenic beauty.",
  "Ross Island": "A historic island with British-era ruins and heritage structures. Offers peaceful vacation with historical exploration.",
  "North Bay Island": "A snorkeling paradise with coral reefs and marine life. Known for glass-bottom boat rides and water activities.",
  "Rock Garden": "A unique art structure made from waste materials showcasing sculpture art. An innovative creation emphasizing environmental awareness.",
  "Sukhna Lake": "A scenic lake in Chandigarh offering boating and recreational activities. Popular for bird watching and picnics.",
  "Rose Garden": "Asia's largest rose garden featuring thousands of rose varieties. Annual rose festival attracts flower enthusiasts.",
  "Capitol Complex": "UNESCO World Heritage Site showcasing modernist architecture. Designed by Le Corbusier, represents India's democratic symbols.",
  "Elante Mall": "A major shopping destination in Chandigarh offering various retail outlets. Modern commercial hub with entertainment facilities.",
  "Pinjore Gardens": "Beautiful Mughal-style gardens featuring cascading water channels. Historic gardens showcasing landscape architecture.",
  "Silvassa": "The capital town of Dadra and Nagar Haveli with tribal culture. Known for Tribal Museum and peaceful environment.",
  "Vanganga Lake Garden": "A scenic garden surrounding Vanganga Lake with island features. Offers recreational activities and natural beauty.",
  "Dudhni Lake": "A water sports hub offering various activities and picnicking. Popular destination for weekend getaway.",
  "Tribal Museum": "Museum showcasing tribal art, culture, and historical artifacts. Represents indigenous heritage and tribal traditions.",
  "Hirwa Van Garden": "A green park featuring waterfalls and scenic landscape. Offers nature walks and recreational activities.",
  "Lion Safari Wildlife Park": "Wildlife safari experience with various animal species. Offers jeep safari and safari photography opportunities.",
  "Diu Fort": "A historic Portuguese fort showcasing colonial architecture. Offers scenic views and historical exploration.",
  "Nagoa Beach": "A popular beach offering water sports and beach activities. Known for scenic beauty and peaceful atmosphere.",
  "Naida Caves": "Natural cave formations with unique geological features. Offers adventure caving experiences.",
  "Jampore Beach": "A peaceful beach known for scenic beauty and solitude. Popular for sunset views and relaxation.",
  "St. Paul's Church": "A colonial church showcasing Portuguese architectural influence. Historic religious site with heritage significance.",
  "Devka Beach": "A scenic shoreline offering beach activities and relaxation. Known for Moti Daman Fort proximity.",
  "Red Fort": "A historic Mughal fort showcasing red sandstone architecture. UNESCO World Heritage Site with historical significance.",
  "India Gate": "A war memorial monument representing India's sacrifices. Iconic structure built to honor soldiers.",
  "Qutub Minar": "The tallest brick minaret in the world with intricate carvings. UNESCO World Heritage Site showcasing medieval architecture.",
  "Lotus Temple": "A unique Bahai temple shaped like a lotus flower. Architectural marvel attracting visitors from all religions.",
  "Chandni Chowk": "A famous historic market in Old Delhi offering shopping and dining. Known for narrow lanes, traditional bazaars, and cultural experiences.",
  "Akshardham Temple": "A modern Hindu temple complex showcasing Indian culture and spirituality. Offers exhibitions and cultural performances."
};

// Read the current file
const placesFilePath = path.join(__dirname, '../backend/data/placesData.js');
const fileContent = fs.readFileSync(placesFilePath, 'utf8');

// Process the file to update descriptions
let updatedContent = fileContent;

// Iterate through each place name and update its description
Object.entries(descriptions).forEach(([placeName, description]) => {
  // Escape special regex characters
  const escapedName = placeName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  
  // Find the place block and update description
  const regex = new RegExp(
    `(name: "${escapedName}",\\s*state: "[^"]*",\\s*stateSlug: "[^"]*",\\s*region: "[^"]*",\\s*category: "[^"]*",\\s*description: ")([^"]*)"`,
    'g'
  );
  
  updatedContent = updatedContent.replace(regex, `$1${description}"`);
});

// Write the updated content back
fs.writeFileSync(placesFilePath, updatedContent, 'utf8');
console.log('✅ Successfully updated descriptions for all places!');
